title = "BluTape"
full_title = "BluTape Mission Generator"
author = "ZeroX"
repo = "https://github.com/0XMagic/BluTape"
version = 6.0
schema_ver = 2
window_size = (1280, 720)
window_pos = (200, 200)
path = "/".join(__file__.split("\\")[:-1]) + "/"
